### ISSUE TITLE
change colors

### ISSUE THREAD

**Issue by Miamoto-Musashi** [aaqibism/platform_date_picker#1]
Hi,
How can I change colors in Material pickers?

nice library btw, thanks

**Comment by aaqibismail** [comment]
Great question. The default Material Date Picker has a builder property where you can pass a Theme object to change the colors. Check out [this thread](https://stackoverflow.com/a/60507705/12425847) on StackOverflow.

**Comment by Miamoto-Musashi** [comment]
maybe you can put a line on the documentation to let others know about it ;)
